# Generated by Django 5.2.13 on 2026-04-17 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='queueentry',
            unique_together=set(),
        ),
    ]
